#!/usr/bin/env node

var VERSION    = process.argv[2]
,   async      = require('async')
,   setup      = require('./lib/setup-directories')
,   git        = require('./lib/git-fetch')(VERSION)
,   zip        = require('./lib/zip') 
